### ISSUE TITLE
half precision xlmr error when model on cpu

### ISSUE THREAD

**Issue by samiwilf** [facebookresearch/FAMBench#40]
Ran into the error screenshotted below.  We could raise a SystemExit when --half-precision (to be added) is passed without --use-gpu, as a possible solution. 
<img width="1042" alt="Screen Shot 2021-10-25 at 12 25 08 AM" src="https://user-images.githubusercontent.com/19678629/138644831-3af7bc0f-4461-40d4-8c71-0c3c38cd9ef4.png">

**Comment by erichan1** [comment]
Not currently fixed. Will loop back to this likely by using bfloat16.
